/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAiReviewRouteImport } from './routes/_authenticated/ai-review'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedCadetsRouteImport } from './routes/_authenticated/cadets'
import { Route as AuthenticatedContentSourcesRouteImport } from './routes/_authenticated/content-sources'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGeoActivityRouteImport } from './routes/_authenticated/geo-activity'
import { Route as AuthenticatedMyExamsRouteImport } from './routes/_authenticated/my-exams'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPdfImportRouteImport } from './routes/_authenticated/pdf-import'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPracticeReviewRouteImport } from './routes/_authenticated/practice-review'
import { Route as AuthenticatedQuestionBankRouteImport } from './routes/_authenticated/question-bank'
import { Route as AuthenticatedExamExamIdRouteImport } from './routes/_authenticated/exam.$examId'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams.index'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results.index'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiReviewRoute = AuthenticatedAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadetsRoute = AuthenticatedCadetsRouteImport.update({
  id: '/cadets',
  path: '/cadets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentSourcesRoute =
  AuthenticatedContentSourcesRouteImport.update({
    id: '/content-sources',
    path: '/content-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeoActivityRoute =
  AuthenticatedGeoActivityRouteImport.update({
    id: '/geo-activity',
    path: '/geo-activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyExamsRoute = AuthenticatedMyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPdfImportRoute = AuthenticatedPdfImportRouteImport.update({
  id: '/pdf-import',
  path: '/pdf-import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeReviewRoute =
  AuthenticatedPracticeReviewRouteImport.update({
    id: '/practice-review',
    path: '/practice-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBankRoute =
  AuthenticatedQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamExamIdRoute = AuthenticatedExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/exams/$examId',
    path: '/exams/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/cadets': typeof AuthenticatedCadetsRoute
  '/content-sources': typeof AuthenticatedContentSourcesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/geo-activity': typeof AuthenticatedGeoActivityRoute
  '/my-exams': typeof AuthenticatedMyExamsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pdf-import': typeof AuthenticatedPdfImportRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/practice-review': typeof AuthenticatedPracticeReviewRoute
  '/question-bank': typeof AuthenticatedQuestionBankRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/cadets': typeof AuthenticatedCadetsRoute
  '/content-sources': typeof AuthenticatedContentSourcesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/geo-activity': typeof AuthenticatedGeoActivityRoute
  '/my-exams': typeof AuthenticatedMyExamsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pdf-import': typeof AuthenticatedPdfImportRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/practice-review': typeof AuthenticatedPracticeReviewRoute
  '/question-bank': typeof AuthenticatedQuestionBankRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-review': typeof AuthenticatedAiReviewRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/cadets': typeof AuthenticatedCadetsRoute
  '/_authenticated/content-sources': typeof AuthenticatedContentSourcesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/geo-activity': typeof AuthenticatedGeoActivityRoute
  '/_authenticated/my-exams': typeof AuthenticatedMyExamsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pdf-import': typeof AuthenticatedPdfImportRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/practice-review': typeof AuthenticatedPracticeReviewRoute
  '/_authenticated/question-bank': typeof AuthenticatedQuestionBankRoute
  '/_authenticated/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-review'
    | '/analysis'
    | '/cadets'
    | '/content-sources'
    | '/dashboard'
    | '/geo-activity'
    | '/my-exams'
    | '/notifications'
    | '/pdf-import'
    | '/practice'
    | '/practice-review'
    | '/question-bank'
    | '/exam/$examId'
    | '/exams/$examId'
    | '/results/$attemptId'
    | '/exams/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-review'
    | '/analysis'
    | '/cadets'
    | '/content-sources'
    | '/dashboard'
    | '/geo-activity'
    | '/my-exams'
    | '/notifications'
    | '/pdf-import'
    | '/practice'
    | '/practice-review'
    | '/question-bank'
    | '/exam/$examId'
    | '/exams/$examId'
    | '/results/$attemptId'
    | '/exams'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ai-review'
    | '/_authenticated/analysis'
    | '/_authenticated/cadets'
    | '/_authenticated/content-sources'
    | '/_authenticated/dashboard'
    | '/_authenticated/geo-activity'
    | '/_authenticated/my-exams'
    | '/_authenticated/notifications'
    | '/_authenticated/pdf-import'
    | '/_authenticated/practice'
    | '/_authenticated/practice-review'
    | '/_authenticated/question-bank'
    | '/_authenticated/exam/$examId'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/exams/'
    | '/_authenticated/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-review': {
      id: '/_authenticated/ai-review'
      path: '/ai-review'
      fullPath: '/ai-review'
      preLoaderRoute: typeof AuthenticatedAiReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadets': {
      id: '/_authenticated/cadets'
      path: '/cadets'
      fullPath: '/cadets'
      preLoaderRoute: typeof AuthenticatedCadetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content-sources': {
      id: '/_authenticated/content-sources'
      path: '/content-sources'
      fullPath: '/content-sources'
      preLoaderRoute: typeof AuthenticatedContentSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geo-activity': {
      id: '/_authenticated/geo-activity'
      path: '/geo-activity'
      fullPath: '/geo-activity'
      preLoaderRoute: typeof AuthenticatedGeoActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-exams': {
      id: '/_authenticated/my-exams'
      path: '/my-exams'
      fullPath: '/my-exams'
      preLoaderRoute: typeof AuthenticatedMyExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdf-import': {
      id: '/_authenticated/pdf-import'
      path: '/pdf-import'
      fullPath: '/pdf-import'
      preLoaderRoute: typeof AuthenticatedPdfImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice-review': {
      id: '/_authenticated/practice-review'
      path: '/practice-review'
      fullPath: '/practice-review'
      preLoaderRoute: typeof AuthenticatedPracticeReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank': {
      id: '/_authenticated/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AuthenticatedQuestionBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$examId': {
      id: '/_authenticated/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof AuthenticatedExamExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiReviewRoute: typeof AuthenticatedAiReviewRoute
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedCadetsRoute: typeof AuthenticatedCadetsRoute
  AuthenticatedContentSourcesRoute: typeof AuthenticatedContentSourcesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGeoActivityRoute: typeof AuthenticatedGeoActivityRoute
  AuthenticatedMyExamsRoute: typeof AuthenticatedMyExamsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPdfImportRoute: typeof AuthenticatedPdfImportRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedPracticeReviewRoute: typeof AuthenticatedPracticeReviewRoute
  AuthenticatedQuestionBankRoute: typeof AuthenticatedQuestionBankRoute
  AuthenticatedExamExamIdRoute: typeof AuthenticatedExamExamIdRoute
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiReviewRoute: AuthenticatedAiReviewRoute,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedCadetsRoute: AuthenticatedCadetsRoute,
  AuthenticatedContentSourcesRoute: AuthenticatedContentSourcesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGeoActivityRoute: AuthenticatedGeoActivityRoute,
  AuthenticatedMyExamsRoute: AuthenticatedMyExamsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPdfImportRoute: AuthenticatedPdfImportRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedPracticeReviewRoute: AuthenticatedPracticeReviewRoute,
  AuthenticatedQuestionBankRoute: AuthenticatedQuestionBankRoute,
  AuthenticatedExamExamIdRoute: AuthenticatedExamExamIdRoute,
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
